site_name: –ë–∞–∑–∞ –∑–Ω–∞–Ω–∏–π –ø–æ —Ä–∞–±–æ—Ç–µ —Å –ø—Ä–∏–ª–æ–∂–µ–Ω–∏—è–º–∏ # –ù–∞–∑–≤–∞–Ω–∏–µ —Å–∞–π—Ç–∞
site_description: –ü–æ—à–∞–≥–æ–≤—ã–µ –∏–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏ –ø–æ —Ä–∞–±–æ—Ç–µ —Å –ø–æ–ø—É–ª—è—Ä–Ω—ã–º–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∞–º–∏ –∏ —Å–µ—Ä–≤–∏—Å–∞–º–∏ # –û–ø–∏—Å–∞–Ω–∏–µ —Å–∞–π—Ç–∞, –¥–æ–±–∞–≤–ª—è–µ—Ç—Å—è –≤ meta-—Ç–µ–≥–∏
site_url: https://example.com # URL —Å–∞–π—Ç–∞ (–∑–∞–º–µ–Ω–∏—Ç–µ –Ω–∞ —Ä–µ–∞–ª—å–Ω—ã–π)
site_author: –ê–≤—Ç–æ—Ä –±–∞–∑—ã –∑–Ω–∞–Ω–∏–π # –ê–≤—Ç–æ—Ä —Å–∞–π—Ç–∞
copyright: Copyright ¬© 2026 # –ò–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ–± –∞–≤—Ç–æ—Ä—Å–∫–∏—Ö –ø—Ä–∞–≤–∞—Ö

theme: # –¢–µ–º–∞ —Å–∞–π—Ç–∞, –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—è –æ –µ–µ –ø–∞—Ä–∞–º–µ—Ç—Ä–∞—Ö
  name: material # –ù–∞–∑–≤–∞–Ω–∏–µ —Ç–µ–º—ã
  logo: images/logo.png # –°—Å—ã–ª–∫–∞ –Ω–∞ –ª–æ–≥–æ—Ç–∏–ø —Å–∞–π—Ç–∞, –ª–æ–≥–æ—Ç–∏–ø –¥–æ–±–∞–≤–ª—è–µ—Ç—Å—è –≤ –ø–∞–ø–∫—É `docs/images`
  favicon: favicon.png # –ò–∫–æ–Ω–∫–∞ —Å–∞–π—Ç–∞ –≤ –±—Ä–∞—É–∑–µ—Ä–µ
  font:
    text: Roboto # –®—Ä–∏—Ñ—Ç —Ç–µ–∫—Å—Ç–∞
    code: Roboto Mono # –®—Ä–∏—Ñ—Ç –¥–ª—è —Ç–µ–∫—Å—Ç–∞ –∫–æ–¥–∞
  language: ru # –Ø–∑—ã–∫
  palette: # –ù–∞—Å—Ç—Ä–æ–π–∫–∏ —Å–≤–µ—Ç–ª–æ–π –∏ —Ç—ë–º–Ω–æ–π —Ç–µ–º
    # –ù–∞—Å—Ç—Ä–æ–π–∫–∏ —Å–≤–µ—Ç–ª–æ–π —Ç–µ–º—ã
    - scheme: default 
      toggle:
        icon: material/weather-sunny # –ò–∫–æ–Ω–∫–∞ –¥–ª—è –∞–∫—Ç–∏–≤–∞—Ü–∏–∏ —Å–≤–µ—Ç–ª–æ–π —Ç–µ–º—ã
        name: –í—ã–∫–ª—é—á–∏—Ç—å —Å–æ–ª–Ω—ã—à–∫–æ # –í—Å–ø–ª—ã–≤–∞—é—â–∏–π —Ç–µ–∫—Å—Ç-–ø–æ–¥—Å–∫–∞–∑–∫–∞
      primary: blue # –û—Å–Ω–æ–≤–Ω–æ–π —Ü–≤–µ—Ç
      accent: indigo # –ê–∫—Ü–µ–Ω—Ç–Ω—ã–π —Ü–≤–µ—Ç
      # –≤—ã –º–æ–∂–µ—Ç–µ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –ª—é–±–æ–π —Ü–≤–µ—Ç –∏–∑ —Å–ø–∏—Å–∫–∞: 
      # red; pink; purple; deep purple; indigo; blue; light blue; cyan; teal; 
      # green; light green; lime; yellow; amber; orange; deep orange; brown; 
      # grey; blue grey; black; white

    # –ù–∞—Å—Ç—Ä–æ–π–∫–∏ —Ç—ë–º–Ω–æ–π —Ç–µ–º—ã
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: –ü–æ–∑–≤–∞—Ç—å —Å–æ–ª–Ω—ã—à–∫–æ
      primary: deep purple
      accent: blue
  features: # –Ω–∞—Å—Ç—Ä–æ–π–∫–∏ —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª—å–Ω–æ—Å—Ç–µ–π —Ç–µ–º—ã
    - navigation.indexes # –ü–æ–∑–≤–æ–ª—è–µ—Ç —Å–æ–∑–¥–∞–≤–∞—Ç—å –∫–æ—Ä–Ω–µ–≤—ã–µ —Å—Ç—Ä–∞–Ω–∏—Ü—ã —Ä–∞–∑–¥–µ–ª–æ–≤ –º–µ–Ω—é. –ö–æ—Ä–Ω–µ–≤–∞—è —Å—Ç—Ä–∞–Ω–∏—Ü–∞ –¥–æ–ª–∂–Ω–∞ –ª–µ–∂–∞—Ç—å –≤ –ø–∞–ø–∫–µ —Ä–∞–∑–¥–µ–ª–∞ –∏ –Ω–∞–∑—ã–≤–∞—Ç—å—Å—è index.md. –ü—Ä–∏–º–µ—Ä –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è –∫–æ—Ä–Ω–µ–≤—ã—Ö —Å—Ç—Ä–∞–Ω–∏—Ü –ø—Ä–∏–≤–µ–¥–µ–Ω –Ω–∏–∂–µ –≤ –Ω–∞—Å—Ç—Ä–æ–π–∫–∞—Ö nav
    - navigation.tabs.sticky # –§–∏–∫—Å–∞—Ü–∏—è –≤–µ—Ä—Ö–Ω–µ–≥–æ –º–µ–Ω—é
    - navigation.instant # –§—É–Ω–∫—Ü–∏—è –±—ã—Å—Ç—Ä–æ–π –∑–∞–≥—Ä—É–∑–∫–∏ —Å—Ç—Ä–∞–Ω–∏—Ü
    - navigation.top # –î–æ–±–∞–≤–ª—è–µ—Ç –∫–Ω–æ–ø–∫—É ¬´–∫ –Ω–∞—á–∞–ª—É¬ª –¥–ª—è –±—ã—Å—Ç—Ä–æ–π –æ–±—Ä–∞—Ç–Ω–æ–π –ø—Ä–æ–∫—Ä—É—Ç–∫–∏ —Å—Ç—Ä–∞–Ω–∏—Ü—ã
    - search.suggest # –ü–æ–¥—Å–∫–∞–∑–∫–∏ –ø—Ä–∏ –≤–≤–æ–¥–µ –ø–æ–∏—Å–∫–æ–≤–æ–≥–æ –∑–∞–ø—Ä–æ—Å–∞
    - search.highlight # –ü–æ–¥—Å–≤–µ—Ç–∫–∞ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–æ–≤ –ø–æ–∏—Å–∫–∞ –≤ —Ç–µ–∫—Å—Ç–µ —Å—Ç—Ä–∞–Ω–∏—Ü—ã
    - content.code.copy # –ö–Ω–æ–ø–∫–∞ –∫–æ–ø–∏—Ä–æ–≤–∞–Ω–∏—è –≤ –±–ª–æ–∫–µ –∫–æ–¥–∞

# –ü–ª–∞–≥–∏–Ω—ã
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+'
      lang: ru
  # - awesome-pages  # –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∏ —Å–æ–±–∏—Ä–∞–µ—Ç –Ω–∞–∑–≤–∞–Ω–∏—è —Å—Ç–∞—Ç–µ–π - –Ω–µ –∑–∞—Ä–∞–±–æ—Ç–∞–ª–æ
  - macros  # –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∏ —Å–æ–±–∏—Ä–∞–µ—Ç –Ω–∞–∑–≤–∞–Ω–∏—è —Å—Ç–∞—Ç–µ–π
  # - tags # –ü–ª–∞–≥–∏–Ω –¥–ª—è —Ç–µ–≥–æ–≤ (—Ä–∞—Å–∫–æ–º–º–µ–Ω—Ç–∏—Ä—É–π—Ç–µ –ø—Ä–∏ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ—Å—Ç–∏)

# –†–∞—Å—à–∏—Ä–µ–Ω–∏—è Markdown
markdown_extensions:
  - admonition # –ë–ª–æ–∫–∏ –ø—Ä–∏–º–µ—á–∞–Ω–∏–π
  - attr_list # –î–æ–±–∞–≤–ª–µ–Ω–∏–µ –∞—Ç—Ä–∏–±—É—Ç–æ–≤ –∫ —ç–ª–µ–º–µ–Ω—Ç–∞–º
  - def_list # –°–ø–∏—Å–∫–∏ –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–∏–π
  - footnotes # –°–Ω–æ—Å–∫–∏
  - md_in_html # Markdown –≤–Ω—É—Ç—Ä–∏ HTML
  - pymdownx.details # –°–≤–æ—Ä–∞—á–∏–≤–∞–µ–º—ã–µ –±–ª–æ–∫–∏
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite # –ü–æ–¥—Å–≤–µ—Ç–∫–∞ –∫–æ–¥–∞ –≤–Ω—É—Ç—Ä–∏ —Å—Ç—Ä–æ–∫
  - pymdownx.snippets # –í–∫–ª—é—á–µ–Ω–∏–µ —Ñ—Ä–∞–≥–º–µ–Ω—Ç–æ–≤
  - pymdownx.superfences # –†–∞—Å—à–∏—Ä–µ–Ω–Ω—ã–µ –±–ª–æ–∫–∏ –∫–æ–¥–∞
  - pymdownx.tabbed:
      alternate_style: true # –í–∫–ª–∞–¥–∫–∏
  - pymdownx.tasklist:
      custom_checkbox: true # –ß–µ–∫–±–æ–∫—Å—ã –≤ —Å–ø–∏—Å–∫–∞—Ö
  - attr_list
  - md_in_html
  - toc:
     permalink: "üîó" # –ü–æ—Å—Ç–æ—è–Ω–Ω—ã–µ —Å—Å—ã–ª–∫–∏ –Ω–∞ –∑–∞–≥–æ–ª–æ–≤–∫–∏

# –ù–∞–≤–∏–≥–∞—Ü–∏—è –ø–æ —Å–∞–π—Ç—É
nav: # –°—Ç—Ä—É–∫—Ç—É—Ä–∞ —Å–∞–π—Ç–∞
- –ì–ª–∞–≤–Ω–∞—è: index.md
- –ú–µ—Å—Å–µ–Ω–¥–∂–µ—Ä—ã:
    - –ú–µ—Å—Å–µ–Ω–¥–∂–µ—Ä—ã: messengers/index.md
    - Telegram: 
        - messengers/telegram/index.md
        - '–°–æ–∑–¥–∞–Ω–∏–µ –≥—Ä—É–ø–ø–æ–≤–æ–≥–æ —á–∞—Ç–∞ –∏ —É–ø—Ä–∞–≤–ª–µ–Ω–∏–µ —É—á–∞—Å—Ç–Ω–∏–∫–∞–º–∏ –≤ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–∏ Telegram': messengers/telegram/tnikonova31-instruction.md
        - '–ü–µ—Ä–µ—Å—ã–ª–∫–∞ —Å–æ–æ–±—â–µ–Ω–∏–π –∏ –º–µ–¥–∏–∞—Ñ–∞–π–ª–æ–≤ –≤ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–∏ Telegram': messengers/telegram/send-messages.md
    - Max:
      - messengers/max/index.md

# –ü–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –∫–∞—Å—Ç–æ–º–Ω—ã—Ö CSS
extra_css:
  - css/custom.css

# –î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–µ –Ω–∞—Å—Ç—Ä–æ–π–∫–∏
extra:
  generator: false # –°–∫—Ä—ã—Ç—å –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ –≥–µ–Ω–µ—Ä–∞—Ç–æ—Ä–µ —Å–∞–π—Ç–∞
  social:
    # - icon: fontawesome/brands/github
    #   link: https://github.com/username
    # - icon: fontawesome/brands/telegram
    #   link: https://t.me/username