site_name: –ë–∞–∑–∞ –∑–Ω–∞–Ω–∏–π –ø–æ —Ä–∞–±–æ—Ç–µ —Å –ø—Ä–∏–ª–æ–∂–µ–Ω–∏—è–º–∏ –∏ –ø—Ä–æ–≥—Ä–∞–º–º–∞–º–∏
site_description: –ü–æ—à–∞–≥–æ–≤—ã–µ –∏–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏ –ø–æ —Ä–∞–±–æ—Ç–µ —Å –ø–æ–ø—É–ª—è—Ä–Ω—ã–º–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∞–º–∏ –∏ —Å–µ—Ä–≤–∏—Å–∞–º–∏
site_url: https://tnikonova31.github.io/MkDocs-site/
site_author: tnikonova31
copyright: Copyright ¬© 2026

theme:
  name: material
  logo: images/logo.png
  favicon: favicon.png
  language: ru

  features:
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+'
      lang: ru
  - tags:
      tags_allowed:
        - –≥–ª–∞–≤–Ω–∞—è
        - –æ–±–∑–æ—Ä
        - –∏–Ω—Å—Ç—Ä—É–∫—Ü–∏–∏
        - –ø—Ä–∏–ª–æ–∂–µ–Ω–∏—è
        - –º–µ—Å—Å–µ–Ω–¥–∂–µ—Ä—ã
        - —á–∞—Ç—ã
        - —Å–æ–æ–±—â–µ–Ω–∏—è
        - telegram
        - —Ñ—É–Ω–∫—Ü–∏–∏
        - –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏
        - max
        - –æ—Ñ–∏—Å
        - –ø—Ä–æ–≥—Ä–∞–º–º—ã
        - –¥–æ–∫—É–º–µ–Ω—Ç—ã
        - api
        - –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è
        - –∑–∞–º–µ—Ç–∫–∏
        - —Ç–µ–∫—Å—Ç–æ–≤—ã–π —Ä–µ–¥–∞–∫—Ç–æ—Ä
        - –≥—Ä–∞—Ñ–∏–∫–∞
  - swagger-ui-tag
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "üîó"

nav:
  - –ì–ª–∞–≤–Ω–∞—è: index.md
  - –ú–µ—Å—Å–µ–Ω–¥–∂–µ—Ä—ã:
      - –û–±–∑–æ—Ä: messengers/index.md
      - Telegram:
          - messengers/telegram/index.md
          - '–°–æ–∑–¥–∞–Ω–∏–µ –≥—Ä—É–ø–ø–æ–≤–æ–≥–æ —á–∞—Ç–∞ –∏ —É–ø—Ä–∞–≤–ª–µ–Ω–∏–µ —É—á–∞—Å—Ç–Ω–∏–∫–∞–º–∏': messengers/telegram/tnikonova31-instruction.md
          - '–ü–µ—Ä–µ—Å—ã–ª–∫–∞ —Å–æ–æ–±—â–µ–Ω–∏–π –∏ –º–µ–¥–∏–∞—Ñ–∞–π–ª–æ–≤': messengers/telegram/send-messages.md
      - MAX:
          - messengers/max/index.md
          - '–ù–∞—Å—Ç—Ä–æ–π–∫–∞ –≤–Ω–µ—à–Ω–µ–≥–æ –≤–∏–¥–∞': messengers/max/appearance.md
          - '–ù–∞—Å—Ç—Ä–æ–π–∫–∞ —É–≤–µ–¥–æ–º–ª–µ–Ω–∏–π': messengers/max/notifications.md
          - '–ù–∞—Å—Ç—Ä–æ–π–∫–∞ –±–µ–∑–æ–ø–∞—Å–Ω–æ—Å—Ç–∏ –∏ –∫–æ–Ω—Ñ–∏–¥–µ–Ω—Ü–∏–∞–ª—å–Ω–æ—Å—Ç–∏': messengers/max/security.md
  - –û—Ñ–∏—Å–Ω—ã–µ –ø—Ä–æ–≥—Ä–∞–º–º—ã:
      - –û—Ñ–∏—Å–Ω—ã–µ –ø—Ä–æ–≥—Ä–∞–º–º—ã: office/index.md
      - Microsoft Word: 
          - office/word/index.md
          - '–í—Å—Ç–∞–≤–∫–∞ —Ç–∞–±–ª–∏—Ü—ã': office/word/table-enter.md
          - '–§–æ—Ä–º–∞—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ —Ç–µ–∫—Å—Ç–∞': office/word/format-text.md
      - –ù–æ—Ç—Å–∞–ø–ø: 
          - office/notesapp/index.md
          - '–°–æ–∑–¥–∞–Ω–∏–µ –∑–∞–º–µ—Ç–∫–∏': office/notesapp/create-note.md
          - '–†–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞–Ω–∏–µ –∑–∞–º–µ—Ç–∫–∏': office/notesapp/edit-note.md
          - '–£–¥–∞–ª–µ–Ω–∏–µ –∑–∞–º–µ—Ç–∫–∏': office/notesapp/delete-note.md               
  - –ì—Ä–∞—Ñ–∏—á–µ—Å–∫–∏–µ –ø—Ä–æ–≥—Ä–∞–º–º—ã:    
      - –ì—Ä–∞—Ñ–∏—á–µ—Å–∫–∏–µ –ø—Ä–æ–≥—Ä–∞–º–º—ã: graphics/index.md
  - API –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è:    
      - API –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è: api/index.md
      - '–ü—Ä–∏–º–µ—Ä API –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏–∏': api/api.md
  # - –¢–µ–≥–∏: tags.md

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
     - icon: fontawesome/brands/github
       link: https://github.com/username  
     - icon: fontawesome/brands/telegram
       link: https://t.me/username
  tags_url: https://tnikonova31.github.io/MkDocs-site/tags/